### ISSUE TITLE
does not build using provided dockerfile

### ISSUE THREAD

**Issue by sneak** [steemit/tinman#137]
Was attempting to snapshot mainnet.  Tried building a docker image from current HEAD on `develop`.

Received the following error.

```
✔ ~/dev/tinman [develop|✔] 
00:03 $ docker build -t steemit/tinman .
Sending build context to Docker daemon  371.2kB
Step 1/8 : FROM python:3.6
3.6: Pulling from library/python
05d1a5232b46: Already exists 
5cee356eda6b: Pull complete 
89d3385f0fd3: Pull complete 
80ae6b477848: Pull complete 
28bdf9e584cc: Pull complete 
dec1a1f0462b: Pull complete 
a4670d125615: Pull complete 
547b45a875f5: Pull complete 
102a0247b454: Pull complete 
Digest: sha256:0c3b6384565b8524a82096bee143174a1f07a28cfdc090ca63c040251ab10604
Status: Downloaded newer image for python:3.6
 ---> 4f13b7f2138e
Step 2/8 : ENV PIPENV_VENV_IN_PROJECT=1
 ---> Running in d04165439841
Removing intermediate container d04165439841
 ---> 43a3e7132e80
Step 3/8 : RUN pip install pipenv
 ---> Running in e1737be0b13b
Collecting pipenv
  Downloading https://files.pythonhosted.org/packages/eb/64/9b2747d54f2008ac3dfe86c0b1c8ec126042726fd8a540d5208d26732701/pipenv-2018.7.1-py3-none-any.whl (5.0MB)
Requirement already satisfied: pip>=9.0.1 in /usr/local/lib/python3.6/site-packages (from pipenv) (18.0)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading https://files.pythonhosted.org/packages/6d/c2/dccb5ccf599e0c5d1eea6acbd058af7a71384f9740179db67a9182a24798/virtualenv_clone-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.6/site-packages (from pipenv) (40.2.0)
Collecting virtualenv (from pipenv)
  Downloading https://files.pythonhosted.org/packages/b6/30/96a02b2287098b23b875bc8c2f58071c35d2efe84f747b64d523721dc2b5/virtualenv-16.0.0-py2.py3-none-any.whl (1.9MB)
Collecting certifi (from pipenv)
  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
Installing collected packages: virtualenv-clone, virtualenv, certifi, pipenv
Successfully installed certifi-2018.8.24 pipenv-2018.7.1 virtualenv-16.0.0 virtualenv-clone-0.3.0
Removing intermediate container e1737be0b13b
 ---> e443e4b0f1b9
Step 4/8 : WORKDIR /tinman
 ---> Running in c67d8be7bf73
Removing intermediate container c67d8be7bf73
 ---> 90b0f09e5545
Step 5/8 : ADD Pipfile Pipfile.lock /tinman/
 ---> c4c7642e44a6
Step 6/8 : RUN pipenv install
 ---> Running in 1da4bd8a1da9
Creating a virtualenv for this project...
Pipfile: /tinman/Pipfile
Using /usr/local/bin/python3.6m (3.6.6) to create virtualenv...
Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local'
New python executable in /tinman/.venv/bin/python3.6m
Also creating executable in /tinman/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /tinman/.venv
Installing dependencies from Pipfile.lock (8d8d0f)...
An error occurred while installing yajl-py==2.1.2! Will try again.
Installing initially failed dependencies...
Looking in indexes: https://pypi.python.org/simple
Collecting yajl-py==2.1.2 
  Using cached https://files.pythonhosted.org/packages/db/a8/01f4ef8eb17f04bef147b1be88975f86c845a78368c33f984e39f5cdaa37/yajl-py-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5ocfz58_/yajl-py/setup.py", line 4, in <module>
        from yajl import __version__ as version
      File "/tmp/pip-install-5ocfz58_/yajl-py/yajl/__init__.py", line 15, in <module>
        from .yajl_common import (
      File "/tmp/pip-install-5ocfz58_/yajl-py/yajl/yajl_common.py", line 56, in <module>
        yajl = load_yajl()
      File "/tmp/pip-install-5ocfz58_/yajl-py/yajl/yajl_common.py", line 43, in load_yajl
        raise OSError('Yajl shared object cannot be found. '
    OSError: Yajl shared object cannot be found. Please install Yajl and confirm it is on your shared lib path.
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5ocfz58_/yajl-py/

The command '/bin/sh -c pipenv install' returned a non-zero code: 1
✘-1 ~/dev/tinman [develop|✔] 
00:05 $ git log | head -1
commit 5a5f38864a0cdd51ae369b4d5339f0eb7d153a1a
✔ ~/dev/tinman [develop|✔] 
00:05 $ 
```

**Comment by inertia186** [comment]
Apparently the Docker file is missing `yajl`:

```bash
apt-get install libyajl-dev
```
